package com.webpick.initializr.git.infrastructure;

import com.webpick.initializr.generation.domain.entities.GenerationContext;
import com.webpick.initializr.git.out.IGitRemotePort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

@Component
public class GithubApiAdapter implements IGitRemotePort {

    private final RestTemplate restTemplate;

    public GithubApiAdapter() {
        this.restTemplate = new RestTemplate();
    }

    // Pour les tests unitaires / mock
    public GithubApiAdapter(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    @Override
    public void pushToRemote(GenerationContext context, byte[] zipContent) {
        String token = context.getGitToken();
        String projectName = context.getProjectName();

        if (token == null || token.trim().isEmpty()) {
            throw new IllegalArgumentException("Token GitHub non fourni.");
        }

        try {
            // 1. Configuration des en-têtes HTTP de l'API GitHub
            HttpHeaders headers = new HttpHeaders();
            headers.set("Authorization", "Bearer " + token);
            headers.set("Accept", "application/vnd.github+json");
            headers.set("X-GitHub-Api-Version", "2022-11-28");
            headers.set("User-Agent", "Webpick-Initializr");

            // 2. Récupération du login de l'utilisateur GitHub connecté
            HttpEntity<Void> entity = new HttpEntity<>(headers);
            ResponseEntity<Map> userResponse = restTemplate.exchange(
                    "https://api.github.com/user",
                    HttpMethod.GET,
                    entity,
                    Map.class
            );
            
            if (userResponse.getBody() == null || !userResponse.getBody().containsKey("login")) {
                throw new RuntimeException("Impossible de récupérer l'identifiant GitHub de l'utilisateur.");
            }
            String username = (String) userResponse.getBody().get("login");

            // 3. Création du dépôt privé GitHub
            Map<String, Object> repoReq = new HashMap<>();
            repoReq.put("name", projectName);
            repoReq.put("private", true);
            repoReq.put("description", "Generated by Webpick Initializr");
            
            HttpEntity<Map<String, Object>> repoEntity = new HttpEntity<>(repoReq, headers);
            try {
                restTemplate.postForEntity("https://api.github.com/user/repos", repoEntity, Map.class);
                System.out.println("Dépôt GitHub créé avec succès : " + username + "/" + projectName);
            } catch (Exception e) {
                // Le dépôt existe peut-être déjà, on continue
                System.out.println("Le dépôt existe déjà ou n'a pas pu être créé (tentative d'écriture) : " + e.getMessage());
            }

            // 4. Extraction du ZIP en mémoire
            Map<String, byte[]> files = new HashMap<>();
            try (ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(zipContent))) {
                ZipEntry entry;
                while ((entry = zis.getNextEntry()) != null) {
                    if (!entry.isDirectory()) {
                        ByteArrayOutputStream bos = new ByteArrayOutputStream();
                        byte[] buffer = new byte[4096];
                        int len;
                        while ((len = zis.read(buffer)) > 0) {
                            bos.write(buffer, 0, len);
                        }
                        files.put(entry.getName(), bos.toByteArray());
                    }
                    zis.closeEntry();
                }
            }

            // 5. Envoi de chaque fichier vers le dépôt via l'API GitHub Contents
            for (Map.Entry<String, byte[]> fileEntry : files.entrySet()) {
                String filePath = fileEntry.getKey();
                byte[] fileBytes = fileEntry.getValue();

                String base64Content = Base64.getEncoder().encodeToString(fileBytes);
                Map<String, Object> commitReq = new HashMap<>();
                commitReq.put("message", "Initial commit from Webpick Initializr");
                commitReq.put("content", base64Content);

                HttpEntity<Map<String, Object>> commitEntity = new HttpEntity<>(commitReq, headers);
                String fileUrl = String.format("https://api.github.com/repos/%s/%s/contents/%s", username, projectName, filePath);

                try {
                    restTemplate.put(fileUrl, commitEntity);
                    System.out.println("Fichier poussé : " + filePath);
                } catch (Exception e) {
                    System.err.println("Échec de la synchronisation du fichier " + filePath + " : " + e.getMessage());
                }
            }

        } catch (Exception e) {
            throw new RuntimeException("Erreur de synchronisation avec l'API GitHub", e);
        }
    }
}