{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "Express application generated by Webpick",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js"
  },
  "dependencies": {
    "express": "^4.18.2"
    <#if database?? && database == "POSTGRES">
    ,"pg": "^8.11.0"
    <#elseif database?? && database == "MYSQL">
    ,"mysql2": "^3.3.0"
    <#elseif database?? && database == "MONGODB">
    ,"mongoose": "^7.2.0"
    </#if>
  },
  "devDependencies": {
    "nodemon": "^2.0.22"
  }
}
